"use client";

import { useState } from "react";

const tabs = [
  { id: "terraform", label: "Terraform Output" },
  { id: "plan", label: "Migration Plan" },
  { id: "checklist", label: "Cutover Checklist" },
];

export default function OutputTabs() {
  const [activeTab, setActiveTab] = useState("terraform");
  
  return (
    <section id="sample-output" className="py-24 relative bg-white dark:bg-slate-950">
      <div className="max-w-[1100px] mx-auto px-6">
        <div className="text-center mb-16">
          <h2 className="text-3xl lg:text-4xl font-bold text-gray-900 dark:text-gray-100 mb-4">Production-Ready Output</h2>
          <p className="text-gray-600 dark:text-gray-400">Not templates. Actual infrastructure code configured for your app.</p>
        </div>
        <div className="flex flex-wrap gap-2 mb-6">
          {tabs.map((tab) => (
            <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`px-5 py-2.5 rounded-lg text-sm font-medium ${activeTab === tab.id ? "bg-blue-600 dark:bg-blue-500 text-white dark:text-black" : "bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400"}`}>{tab.label}</button>
          ))}
        </div>
        <div className="bg-gray-50 dark:bg-[#0d1117] border border-gray-200 dark:border-gray-800 rounded-2xl p-6 overflow-x-auto">
          {activeTab === "terraform" && (
            <pre className="font-mono text-sm text-gray-700 dark:text-gray-300">{`# Generated by MigrateIQ
# Source: Heroku app "production"

resource "aws_ecs_service" "web" {
  name            = "production-web"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.web.arn
  desired_count   = 2
  launch_type     = "FARGATE"
  
  network_configuration {
    subnets         = aws_subnet.private[*].id
    security_groups = [aws_security_group.ecs.id]
  }
}

resource "aws_db_instance" "postgres" {
  identifier     = "production-db"
  engine         = "postgres"
  engine_version = "15.4"
  instance_class = "db.t3.medium"
  # ... 47 more lines
}`}</pre>
          )}
          {activeTab === "plan" && (
            <div className="space-y-4 text-sm">
              <div className="p-4 rounded-lg bg-blue-50 dark:bg-blue-950/20 border border-blue-200 dark:border-blue-900/30">
                <p className="font-semibold text-blue-700 dark:text-blue-400 mb-2">Phase 1: Infrastructure (Day 1)</p>
                <ul className="text-gray-600 dark:text-gray-400 space-y-1 ml-4">
                  <li>• Create VPC, subnets, security groups</li>
                  <li>• Provision RDS PostgreSQL</li>
                  <li>• Set up ElastiCache Redis</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-900/30">
                <p className="font-semibold text-amber-700 dark:text-amber-400 mb-2">Phase 2: Data Migration (Day 2-3)</p>
                <ul className="text-gray-600 dark:text-gray-400 space-y-1 ml-4">
                  <li>• Set up database replication</li>
                  <li>• Migrate Redis data</li>
                  <li>• Sync secrets to Secrets Manager</li>
                </ul>
              </div>
              <div className="p-4 rounded-lg bg-emerald-50 dark:bg-emerald-950/20 border border-emerald-200 dark:border-emerald-900/30">
                <p className="font-semibold text-emerald-700 dark:text-emerald-400 mb-2">Phase 3: Cutover (Day 4)</p>
                <ul className="text-gray-600 dark:text-gray-400 space-y-1 ml-4">
                  <li>• Deploy application to ECS</li>
                  <li>• Run smoke tests</li>
                  <li>• Update DNS records</li>
                </ul>
              </div>
            </div>
          )}
          {activeTab === "checklist" && (
            <div className="space-y-3 text-sm">
              {["Terraform applied successfully", "Database replication lag < 1s", "All secrets migrated", "Health checks passing", "Load balancer configured", "SSL certificates valid", "Monitoring alerts configured", "Rollback plan documented"].map((item, i) => (
                <div key={i} className="flex items-center gap-3 p-3 rounded-lg bg-gray-100 dark:bg-gray-800/50">
                  <input type="checkbox" className="w-4 h-4 accent-blue-500" defaultChecked={i < 3} />
                  <span className="text-gray-700 dark:text-gray-300">{item}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
